version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: "Actions"
- package-ecosystem: gradle
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: "Gradle"